### ISSUE TITLE
error

### ISSUE THREAD

**Issue by arnavaz** [PoisonAlien/basecounts#1]
Hi I get the following error when I run basecounts tool:
```
chr	pos	refbase	spaceholder	"sample_id.processed"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Fetch', src/bambases.rs:67:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
My command is:
`./target/release/basecounts -a -v /cluster/home/arna/basecounts/test.bed /path/input/sample_id.processed.bam`

Could you please let me know what is wrong with my run?
Thanks!
Arna

**Comment by PoisonAlien** [comment]
Hi,

This repository is no longer maintained. I would recommend this [ntcounts](https://gist.github.com/PoisonAlien/4a5fcc2126a731417671c4738bcd94cc) instead. 

```
git clone https://gist.github.com/PoisonAlien/4a5fcc2126a731417671c4738bcd94cc
cd 4a5fcc2126a731417671c4738bcd94cc

#compile 
gcc -g -O3 -pthread ntcounts.c -lhts -Ihts -o ntcounts


#usage
./ntcounts
-------------------------------------------------------------------------
ntcounts: A tool to extract nucleotide counts
          of genomic loci from the BAM file. Version: 0.1.0
USAGE:
    ntcounts [OPTIONS] <loci> <bam>
    e.g; ntcounts target_loci.tsv Tumor.bam
OPTIONS:
    -f  Indexed fasta file. If provided, extracts and adds reference base to the ouput tsv
    -q  Min. mapping quality threshold. Default 10 [Read filter]
    -F  Exclude reads with FLAGS >= INT. Default 3852 [Read filter]
    -o  Output file basename. Default parses from basename of BAM file
ARGS:
    <loci>   variant file (chr\tpos)
    <bam>    Indexed BAM file
OUPUT:
    <output>.tsv    TSV file with nucletide counts for all variants
-------------------------------------------------------------------------
```

Let me know if you get any issues.

**Comment by arnavaz** [comment]
Thanks a lot,
I ran the compilation command and I get the following error:
```
ntcounts.c:13:24: fatal error: htslib/sam.h: No such file or directory
 #include <htslib/sam.h>
                        ^
compilation terminated.
```
Do you know why? I really appreciate your help,

**Comment by PoisonAlien** [comment]
Hi,

Forgot to mention. You need to install [htslib](https://github.com/samtools/htslib)

**Comment by arnavaz** [comment]
I see. If I have samtools installed would it help if I loaded it?

**Comment by PoisonAlien** [comment]
I don't know tbh. But you will need the `htslib` library installed (which is also what samtools depends on).

**Comment by arnavaz** [comment]
Thank you,
I installed ntcounts and tried it. It only reports 0 for all the loci and all basepair letters..
Do you know why this could happen? I know there are reads at the given locations but ntcounts is reporting zero for all of them.

**Comment by PoisonAlien** [comment]
Hi,
One reason I can think of is the `chr` prefixes. Make sure the chromosome names match between the BAM file and the loci file.

**Comment by arnavaz** [comment]
Thanks this solved the issue.
